### PR TITLE
WIP: Twitter_Bot : Introduced logger instance to replace current logging mechanism

### PR DESCRIPTION
**Pull request by ananthanandanan**
- Setting up a logger instances for results.log and error.log to log the messages to the default directory.
- There are two methods used:
    - setup_logger() - this method  create an logger for both the log files
    - logger() : This method takes in the filename, level and the message that needs to be logged.

### CODE REVIEW

**Comment by Aniketh01** [comment]
> Here when the check_tweet() is called, it will iterate through and check if the tweet_id is a stored tweet or not.,  

Wasn't this part of another commit? which is already merged?

**Review by Aniketh01 — COMMENTED** [review]
Logger is added. But not used yet. Migarate the current logging mechanism to this.

**Comment by ananthanandanan** [comment]
I have now added the logger method through out the twitter_bot. But currently I will be able to store the logs in results.log and error.log in /var/tmp.

**Review by Aniketh01 — COMMENTED** [review]
Thanks for the changes. It could have been another commit, the usage of logger module in twitter bot.

**Comment by Aniketh01** [comment]
Also I hope there is not changes to tid_store, right?

**Comment by ananthanandanan** [comment]
No I only made changes so as to store the logs into a file. The tid_store.txt remains untouched, since it is a work for another PR.

**Comment by Aniketh01** [comment]
Okay, rather than rebasing the addition of logger usage, spilt that to a different commit and add logger support for telegram bot as well. Keep all as separate commits.

Let us merge this and we can think about the default location later.

**Comment by ananthanandanan** [comment]
So in the second commit logger is added for both tb_bot and twitter_bot right?

**Comment by ananthanandanan** [comment]
Is this commit message ok?.

**Comment by Aniketh01** [comment]
@ananthanandanan have you changed the default_dir path

**Comment by ananthanandanan** [comment]
Not in the commit.

**Pull request closed without merging**
