### PR TITLE
Added requirements.txt file

### PR DESCRIPTION
**Pull request by ananthanandanan**
### Added requirements.txt file

- This file contains the required list of packages for the project.

### CODE REVIEW

**Comment by Aniketh01** [comment]
Is this the confirmed list of requirements?

Can I get a +1 from @iammarco11 as well?

**Comment by iammarco11** [comment]
Okay there are still some unnecessary packages, I have listed the necessary one
```
certifi==2020.4.5.1
chardet==3.0.4
idna==2.9
oauthlib==3.1.0
pkg-resources==0.0.0
PySocks==1.7.1
requests==2.23.0
requests-oauthlib==1.3.0
six==1.14.0
tweepy==3.8.0
urllib3==1.25.8
```
Just can you check from your side as well, @ananthanandanan?

**Comment by Aniketh01** [comment]
Looks good. Once the PR is updated, let me know. I will merge :)

**Comment by ananthanandanan** [comment]
@iammarco11  I don't think pkg-resources is needed. For reference https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command

**Comment by iammarco11** [comment]
Oh yea excluding that
 Can you update the PR?

**Comment by ananthanandanan** [comment]
Does this is it LG.

**Comment by iammarco11** [comment]
Can you remove the unwanted changes in the `gitignore` file?

Otherwise LGTM

**Comment by iammarco11** [comment]
@Aniketh01 I guess all the required packages are there.

**Comment by ananthanandanan** [comment]
Yes.

**Comment by Aniketh01** [comment]
Merged and close! :)

**Pull request merged**
